name: Debug Build
run-name: Building simplesound Debug Build
on:
  workflow_dispatch:
    inputs:
      job_targets:
        description: 'Select the platform'
        required: true
        default: 'linux'
        type: choice
        options:
          - linux
          - windows
          - all

env:
  GODOT_VERSION: 4.7
  GODOT_PROJECT_LOCATION: project.godot
  EXPORT_FOLDER_LINUX: bin/Linux
  EXPORT_FOLDER_WINDOWS: bin/Windows
  EXPORT_FOLDER_MACOS: bin/MacOS
  APPLICATION_NAME: simplesound

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Setting extra variables
        run: |
          echo "MAIN_FOLDER=$(pwd)" >> $GITHUB_ENV
      - name: Installing dependencies
        run: pacman -Syu --noconfirm git bash yasm python python-pip scons gcc diffutils make wget unzip tar mingw-w64 dotnet-sdk
      - name: Prepare Godot
        run: |
          wget -q -O godot_linux.zip https://github.com/godotengine/godot-builds/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_mono_linux_x86_64.zip
          unzip godot_linux.zip
          mv Godot_v${{ env.GODOT_VERSION }}-stable_mono_linux_x86_64/* .
          wget -q -O godot_export_templates.tpz https://github.com/godotengine/godot-builds/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_mono_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable
          unzip godot_export_templates.tpz -d ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable
          mv ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable/templates/* ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable/
      - name: Building debug Linux
        if: ${{ github.event.inputs.job_targets == 'linux' || github.event.inputs.job_targets == 'all'}}
        run: |
          mkdir -p ${{ env.EXPORT_FOLDER_LINUX }}
          ./Godot_v${{ env.GODOT_VERSION }}-stable_mono_linux.x86_64 --import ${{ env.GODOT_PROJECT_LOCATION }} --quiet --headless --export-debug Linux ${{ env.MAIN_FOLDER }}/${{ env.EXPORT_FOLDER_LINUX }}/${{ env.APPLICATION_NAME }}.x86_64
          chmod +x ${{ env.EXPORT_FOLDER_LINUX }}/${{ env.APPLICATION_NAME }}.sh
          chmod +x ${{ env.EXPORT_FOLDER_LINUX }}/${{ env.APPLICATION_NAME }}.x86_64
      - name: Tar files
        if: ${{ github.event.inputs.job_targets == 'linux' || github.event.inputs.job_targets == 'all'}}
        run: tar -cvf ${{ env.APPLICATION_NAME }}_linux_debug.tar ${{ env.EXPORT_FOLDER_LINUX }}
      - name: Uploading artifact debug Linux
        if: ${{ github.event.inputs.job_targets == 'linux' || github.event.inputs.job_targets == 'all'}}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APPLICATION_NAME }}_linux_debug.tar
          path: ${{ env.APPLICATION_NAME }}_linux_debug.tar
      - name: Building debug Windows
        if: ${{ github.event.inputs.job_targets == 'windows' || github.event.inputs.job_targets == 'all'}}
        run: |
          mkdir -p ${{ env.EXPORT_FOLDER_WINDOWS }}
          ./Godot_v${{ env.GODOT_VERSION }}-stable_mono_linux.x86_64 --import ${{ env.GODOT_PROJECT_LOCATION }} --quiet --headless --export-debug Windows ${{ env.MAIN_FOLDER }}/${{ env.EXPORT_FOLDER_WINDOWS }}/${{ env.APPLICATION_NAME }}.exe
      - name: Uploading artifact debug Windows
        if: ${{ github.event.inputs.job_targets == 'linux' || github.event.inputs.job_targets == 'all'}}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APPLICATION_NAME }}_windows_debug.tar
          path: ${{ env.EXPORT_FOLDER_WINDOWS }}/